INSERT INTO fixtures VALUES (1);
INSERT INTO fixtures VALUES ('A01');
INSERT INTO fixtures VALUES ('A02');

INSERT INTO employees VALUES (1);
INSERT INTO employees VALUES (2);
INSERT INTO employees VALUES (3);
